/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tutorplus.views;
import com.tutorplus.controllers.TutorialClient;

import com.tutorplus.application_core.QuestionOptions;
import com.tutorplus.application_core.TopicQuestions;
import java.awt.HeadlessException;
import java.rmi.RemoteException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import static java.util.Comparator.comparing;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import oracle.jdbc.dcn.DatabaseChangeEvent;

/**
 *
 * @author elleb
 */
public class StudentTutorial extends javax.swing.JFrame {
    
    protected  String topicId;
    protected  HashMap<String,TopicQuestions> topicQuestions;
    protected  HashMap<String,QuestionOptions> questionOptions;
    private  double numOfQuestions;
    private  int nextQuestionCounter =1;
    private  double userScore= 0; 
    private  TopicQuestions currentQuestion;
    private  List<String> currentQuestionOptions;
    private boolean initialized = false;
    private boolean isRestartTutorial = false;
    
    /**
     * Creates new form StudentTutorial
     */
    public StudentTutorial() {
        initComponents();
    }
    
    public StudentTutorial(String topicId){
        
        try {
           if (TutorialClient.user != null) {
                topicId = topicId.toUpperCase();
                this.topicId = topicId;
                this.topicQuestions = TutorialClient.tutorplusIntf.getTopicQuestions(topicId);
                this.questionOptions = TutorialClient.tutorplusIntf.getQuestionOptions(topicId);
                this.numOfQuestions = this.topicQuestions.size();
                this.currentQuestionOptions= new ArrayList<>();
                
                System.out.println(this.numOfQuestions);

                getNextQuestionAndOptions(topicId);
            }
            
            initComponents();
        
        }catch (RemoteException e){
            e.printStackTrace();
        }
        
    }

    private void getNextQuestionAndOptions(String topicId1) {
        
        //get next question
        this.currentQuestion = this.topicQuestions.get(topicId1 + "_Q" + this.nextQuestionCounter);
        
        
        //get options for next quesiton
        if (!this.currentQuestionOptions.isEmpty()) this.currentQuestionOptions.clear(); //clear array to load new set of options
        Iterator iterator = this.questionOptions.entrySet().iterator();
        while (iterator.hasNext()){
            
            Map.Entry pair = (Map.Entry)iterator.next();
            
            System.out.println(pair.getKey() + " = " + pair.getValue());
            
            QuestionOptions option = (QuestionOptions) pair.getValue();
            
            if (option.getQuestionId().equalsIgnoreCase("Q"+this.nextQuestionCounter)){
                
                this.currentQuestionOptions.add(option.getOptionId()+") "+option.getOption());
                
                Collections.sort(this.currentQuestionOptions, (String optionId1, String optionId2) ->{
                    return optionId1.compareToIgnoreCase(optionId2);
                });
                
            }
            
        }
        if (this.initialized) {
            //elements to update
            AnswerList.clearSelection();
            AnswerList.setModel(new javax.swing.AbstractListModel<String>() {
                 
                public int getSize() { return currentQuestionOptions.size(); }
                public String getElementAt(int i) { return currentQuestionOptions.get(i); }
            });
            
            Question.setText("Question "+this.nextQuestionCounter+" : "+ this.currentQuestion.getQuestion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.initialized = true;
        jPanel1 = new javax.swing.JPanel();
        MyProfileJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ViewStudentInfo = new javax.swing.JButton();
        LogOutStudent = new javax.swing.JButton();
        TutorialJPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        CourseTutorialList = new javax.swing.JList<>();
        OpenTutorial = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AnswerList = new javax.swing.JList<>();
        SubmitAnswer = new javax.swing.JButton();
        GoToNextQuestion = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        MyDashboardMenu = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MyProfileJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("My Profile"));

        jLabel1.setText("Welcome");

        jLabel2.setText(TutorialClient.user.getFirstName() +" "+ TutorialClient.user.getLastName());

        ViewStudentInfo.setText("View my information");
        ViewStudentInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewStudentInfoMouseClicked(evt);
            }
        });

        LogOutStudent.setText("Log Out");
        LogOutStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MyProfileJPanelLayout = new javax.swing.GroupLayout(MyProfileJPanel);
        MyProfileJPanel.setLayout(MyProfileJPanelLayout);
        MyProfileJPanelLayout.setHorizontalGroup(
            MyProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyProfileJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MyProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyProfileJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(MyProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LogOutStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewStudentInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MyProfileJPanelLayout.setVerticalGroup(
            MyProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyProfileJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MyProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(ViewStudentInfo)
                .addGap(18, 18, 18)
                .addComponent(LogOutStudent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TutorialJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("My Tutorials"));

        CourseTutorialList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(CourseTutorialList);

        OpenTutorial.setText("Open Tutorial");
        OpenTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenTutorialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TutorialJPanelLayout = new javax.swing.GroupLayout(TutorialJPanel);
        TutorialJPanel.setLayout(TutorialJPanelLayout);
        TutorialJPanelLayout.setHorizontalGroup(
            TutorialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TutorialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addGroup(TutorialJPanelLayout.createSequentialGroup()
                        .addComponent(OpenTutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TutorialJPanelLayout.setVerticalGroup(
            TutorialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(OpenTutorial)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(MyProfileJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TutorialJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MyProfileJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(TutorialJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        PageLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PageLabel.setText("Tutorial Topic: "+this.currentQuestion.getTopicName());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PageLabel)
                .addContainerGap(579, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Question.setText("Question "+this.nextQuestionCounter+" : "+ this.currentQuestion.getQuestion());

        AnswerList.setModel(new javax.swing.AbstractListModel<String>() {
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            
            public int getSize() { return currentQuestionOptions.size(); }
            public String getElementAt(int i) { return currentQuestionOptions.get(i); }
        });
        
        jScrollPane1.setViewportView(AnswerList);

        SubmitAnswer.setText("Submit");
        SubmitAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitAnswerMouseClicked(evt);
            }
        });

        GoToNextQuestion.setText("Next Question");
        GoToNextQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoToNextQuestionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SubmitAnswer)
                        .addGap(33, 33, 33)
                        .addComponent(GoToNextQuestion))
                    .addComponent(Question)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Question)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitAnswer)
                    .addComponent(GoToNextQuestion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MyDashboardMenu.setText("My Dashboard");
        MyDashboardMenu.setActionCommand("");
        MyDashboardMenu.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        MyDashboardMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyDashboardMenuMouseClicked(evt);
            }
        });
        MenuBar.add(MyDashboardMenu);

        Exit.setText("Exit");
        Exit.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        MenuBar.add(Exit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyDashboardMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyDashboardMenuMouseClicked
        // TODO add your handling code here:
        StudentDashboard regFace =new StudentDashboard();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_MyDashboardMenuMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void ViewStudentInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewStudentInfoMouseClicked
        // TODO add your handling code here:
        EditStudent regFace =new EditStudent();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewStudentInfoMouseClicked

    private void LogOutStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutStudentMouseClicked
        // TODO add your handling code here:
        Login regFace =new Login();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutStudentMouseClicked

    private void OpenTutorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenTutorialMouseClicked
        // TODO add your handling code here:        
        
        String tut = CourseTutorialList.getSelectedValue();  
        
        StudentTutorial regFace =new StudentTutorial();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpenTutorialMouseClicked

    private void SubmitAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitAnswerMouseClicked
        // TODO add your handling code here:
        if (TutorialClient.user != null){
            if (this.isRestartTutorial != true){
                String submittedOption = AnswerList.getSelectedValue();
                if (submittedOption != null){
                    String submittedAns = submittedOption.substring(0,1);

    //                if (this.nextQuestionCounter != this.numOfQuestions){
                        if (this.currentQuestion.getAnswer().equalsIgnoreCase(submittedAns)){
                            this.userScore++;
                            JOptionPane.showMessageDialog(null,submittedAns + " is correct! ");
        //                    this.getNextQuestionAndOptions(this.topicId);
                        }
                        else {
                                JOptionPane.showMessageDialog(null, "Sorry, "+submittedAns + " is incorrect ");
        //                        this.nextQuestionCounter++;
                        }
    //                }
                   if (this.nextQuestionCounter < this.numOfQuestions){
                        this.nextQuestionCounter++;
                        if (this.nextQuestionCounter == numOfQuestions) {
                            this.GoToNextQuestion.setText("End of questions");
                        }

                        this.getNextQuestionAndOptions(this.topicId);
                    }
                    else {
                        this.isRestartTutorial = true;
                        this.SubmitAnswer.setEnabled(false);
                        tallyScoreAndGiveOptionToRestart();

                    }
                }
            }
        }
    }//GEN-LAST:event_SubmitAnswerMouseClicked

    private void GoToNextQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoToNextQuestionMouseClicked
       
        if (TutorialClient.user != null){
            
            if (!this.isRestartTutorial){//go to next question
                
                if (this.nextQuestionCounter < this.numOfQuestions){
                    this.nextQuestionCounter++;
                    this.getNextQuestionAndOptions(this.topicId);

                }
                else { //end of tutorial
//                    this.isRestartTutorial = true;
//                    tallyScoreAndGiveOptionToRestart();
                      this.GoToNextQuestion.setText("End of questions");

                }
            }
            else {//restart tutorial
                StudentTutorial regFace =new StudentTutorial(this.topicId);
                regFace.setVisible(true);
                dispose();
            }
        }

        
    }//GEN-LAST:event_GoToNextQuestionMouseClicked

    private void tallyScoreAndGiveOptionToRestart() throws HeadlessException {
        GoToNextQuestion.setText("Restart Tutorial");
        DecimalFormat percentageFormat = new DecimalFormat("###.#%");
        double percentageGained = this.userScore / this.numOfQuestions;
        
        JOptionPane.showMessageDialog(null,"You score is:" + percentageFormat.format(percentageGained ));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentTutorial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AnswerList;
    private javax.swing.JList<String> CourseTutorialList;
    private javax.swing.JMenu Exit;
    private javax.swing.JButton GoToNextQuestion;
    private javax.swing.JButton LogOutStudent;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MyDashboardMenu;
    private javax.swing.JPanel MyProfileJPanel;
    private javax.swing.JButton OpenTutorial;
    private javax.swing.JLabel PageLabel;
    private javax.swing.JLabel Question;
    private javax.swing.JButton SubmitAnswer;
    private javax.swing.JPanel TutorialJPanel;
    private javax.swing.JButton ViewStudentInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
